#!/usr/bin/env python3
"""Validate a generated company AI organization scaffold."""

from __future__ import annotations

import argparse
import re
import stat
import sys
from pathlib import Path


SECRET_PATTERNS = {
    "OpenAI-like secret": re.compile(r"\bsk-[A-Za-z0-9_-]{16,}\b"),
    "AWS access key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "GitHub token": re.compile(r"\bgh[opsu]_[A-Za-z0-9]{20,}\b"),
    "Google API key": re.compile(r"\bAIza[0-9A-Za-z_-]{30,}\b"),
    "email address": re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"),
    "phone-like number": re.compile(r"(?:\b0\d{1,4}[- ]?\d{1,4}[- ]?\d{3,4}\b|\+\d{10,15}\b)"),
}

REQUIRED_ROOT_PHRASES = [
    "AGENTS.md",
    "人間承認",
    "外部送信",
    "パスワード",
    "APIキー",
    "人間承認済み",
    "サンドボックス",
    "人間承認後だけ「人間承認済み」",
    "@安全・法務責任者AI",
    "@品質確認責任者AI",
]

FORBIDDEN_BEGINNER_TEXT = [
    ("英語の管理項目", re.compile(r"(?m)^(?:created_at|purpose|status|next_action|human_approval_required):")),
    ("英語の状態ID", re.compile(r"\b(?:draft|reviewed|qa_review|approved)\b")),
    ("英語の情報分類ID", re.compile(r"`(?:public|internal|confidential|restricted)`")),
    ("古い安全・法務の役割名", re.compile(r"@品質法務・情報セキュリティ責任者AI")),
    ("古い品質確認の役割名", re.compile(r"@進行品質監査責任者AI")),
    ("初心者向けで使わない専門用語", re.compile(r"実企業の非公開ドラフト|ドラフト|インシデント")),
]

MANDATORY_DEPARTMENT_FOLDERS = [
    "10_IT・AI管理",
    "11_安全・法務",
    "12_品質確認",
]

REQUIRED_DEPARTMENT_PHRASES = [
    "上位ルール",
    "責任者",
    "担当できる作業",
    "担当してはいけない作業",
    "責任者を通す条件",
    "人間承認",
    "引き継ぎ",
    "完了条件",
]


def add(errors: list[str], message: str) -> None:
    errors.append(message)


def validate(root: Path) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    root = root.resolve()
    if not root.is_dir():
        return [f"not a directory: {root}"], warnings
    if "skills" in {part.lower() for part in root.parts}:
        add(errors, "generated output must not be inside any skills directory")
    for ancestor in (root, *root.parents):
        if (ancestor / ".git").exists():
            add(errors, "generated output must not be inside a Git-managed directory")
            break

    required = [
        root / "README.md",
        root / "AGENTS.md",
        root / "00_会社統括" / "AGENTS.md",
        root / "00_会社統括" / "誰が確認するか.md",
        root / "00_会社統括" / "情報分類ルール.md",
        root / "00_会社統括" / "AI担当一覧.md",
        root / "00_会社統括" / "兼務一覧.md",
        root / "00_会社統括" / "事故・漏えい時の初動.md",
        root / "90_共通テンプレート" / "作業依頼テンプレート.md",
        root / "90_共通テンプレート" / "完了報告テンプレート.md",
        root / "98_作業記録" / "README.md",
        root / "99_未確定" / "README.md",
    ]
    for path in required:
        if not path.is_file():
            add(errors, f"missing required file: {path.relative_to(root)}")

    all_paths = list(root.rglob("*"))
    if any(path.is_symlink() for path in all_paths):
        add(errors, "symlinks are not allowed in the starter")
    if any(path.name == ".git" for path in all_paths):
        add(errors, "generated customer output must not contain a .git directory")
    bad_agent_names = [path for path in all_paths if path.is_file() and path.name.lower() == "agent.md"]
    if bad_agent_names:
        add(errors, "found agent.md; Codex default is AGENTS.md")
    override_files = [path for path in all_paths if path.name == "AGENTS.override.md"]
    if override_files:
        add(errors, "AGENTS.override.md is not generated by this baseline because it would replace normal instructions in the same directory")

    all_files = [path for path in all_paths if path.is_file()]
    non_markdown = [path for path in all_files if path.suffix.lower() != ".md"]
    for path in non_markdown:
        add(errors, f"unexpected non-Markdown file: {path.relative_to(root)}")
    markdown_files = [path for path in all_files if path.suffix.lower() == ".md"]
    combined_text = ""
    for path in markdown_files:
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError) as exc:
            add(errors, f"cannot safely read UTF-8 file {path.relative_to(root)}: {exc}")
            continue
        combined_text += "\n" + text
        if re.search(r"(?m)^状態:\s*人間承認済み\s*$", text):
            add(errors, f"生成直後なのに人間承認済みと記録されています: {path.relative_to(root)}")
        for reason, pattern in FORBIDDEN_BEGINNER_TEXT:
            if pattern.search(text):
                add(errors, f"初心者向け生成物に{reason}があります: {path.relative_to(root)}")
                break
        if path.name == "AGENTS.md":
            lines = len(text.splitlines())
            if lines > 200:
                add(errors, f"AGENTS.md exceeds 200 lines ({lines}): {path.relative_to(root)}")
            if not re.search(r"(?m)^状態:\s*下書き\s*$", text):
                add(errors, f"AGENTS.mdに「状態: 下書き」がありません: {path.relative_to(root)}")
            if not re.search(r"(?m)^人間確認が必要:\s*はい\s*$", text):
                add(errors, f"AGENTS.mdに人間確認の必須表示がありません: {path.relative_to(root)}")
            if "責任者AIが作業範囲を承認" in text:
                add(errors, f"AI must review, not approve work scope: {path.relative_to(root)}")
        if sys.platform != "win32" and stat.S_IMODE(path.stat().st_mode) != 0o600:
            add(errors, f"file must use exact mode 600: {path.relative_to(root)}")

    for label, pattern in SECRET_PATTERNS.items():
        if pattern.search(combined_text):
            add(errors, f"possible secret detected: {label}")

    root_agents = root / "AGENTS.md"
    if root_agents.is_file():
        text = root_agents.read_text(encoding="utf-8")
        for phrase in REQUIRED_ROOT_PHRASES:
            if phrase not in text:
                add(errors, f"root AGENTS.md missing phrase: {phrase}")

    readme = root / "README.md"
    if readme.is_file():
        readme_text = readme.read_text(encoding="utf-8")
        for phrase in (
            "今回は作らない部署",
            "あとで確認する部署",
            "部署番号が途中で飛んでいても問題ではない",
            "## 最初の1回",
            "00_会社統括/AI担当一覧.md",
            "90_共通テンプレート/作業依頼テンプレート.md",
            "90_共通テンプレート/完了報告テンプレート.md",
            "@会社統括責任者AIとして",
            "@営業責任者AIとして",
        ):
            if phrase not in readme_text:
                add(errors, f"README.mdに部署の作成判断の説明がありません: {phrase}")

    classification = root / "00_会社統括" / "情報分類ルール.md"
    if root_agents.is_file() and classification.is_file():
        root_text = root_agents.read_text(encoding="utf-8")
        classification_text = classification.read_text(encoding="utf-8")
        if "非公開情報の入力禁止" in root_text:
            for label in ("社内情報", "機密情報", "特に注意が必要な情報"):
                if not re.search(rf"^- {label}:.*外部AIへ入力禁止", classification_text, re.MULTILINE):
                    add(errors, f"情報分類ルールが外部AI入力禁止設定と一致しません: {label}")
            if "明示許可なし" in classification_text or "原則入力禁止" in classification_text:
                add(errors, "外部AI入力禁止設定に例外を示す弱い表現があります")

    controller = root / "00_会社統括"
    department_dirs = sorted(
        path for path in controller.iterdir()
        if path.is_dir() and (path / "AGENTS.md").is_file()
    ) if controller.is_dir() else []
    if not department_dirs:
        add(errors, "no active department folders found")
    for folder in MANDATORY_DEPARTMENT_FOLDERS:
        if not (controller / folder / "AGENTS.md").is_file():
            add(errors, f"missing mandatory control department: {folder}")

    labels = []
    for department in department_dirs:
        agents = department / "AGENTS.md"
        role = department / "AI社員" / "役割定義.md"
        prevention = department / "ミス防止ルール.md"
        if not role.is_file():
            add(errors, f"missing AI role definition: {role.relative_to(root)}")
        if not prevention.is_file():
            add(errors, f"missing mistake-prevention file: {prevention.relative_to(root)}")
        text = agents.read_text(encoding="utf-8")
        for phrase in REQUIRED_DEPARTMENT_PHRASES:
            if phrase not in text:
                add(errors, f"{agents.relative_to(root)} missing phrase: {phrase}")
        title = text.splitlines()[0] if text.splitlines() else ""
        if title in labels:
            add(errors, f"duplicate department title: {title}")
        labels.append(title)

        instruction_bytes = sum(
            path.stat().st_size
            for path in (root / "AGENTS.md", controller / "AGENTS.md", agents)
            if path.is_file()
        )
        if instruction_bytes > 32 * 1024:
            add(errors, f"instruction chain exceeds 32KiB at {department.name}: {instruction_bytes} bytes")

    for directory in [root, *[path for path in all_paths if path.is_dir()]]:
        if not any(directory.iterdir()):
            add(errors, f"empty directory: {directory.relative_to(root)}")
        if sys.platform != "win32" and stat.S_IMODE(directory.stat().st_mode) != 0o700:
            add(errors, f"directory must use exact mode 700: {directory.relative_to(root) if directory != root else '.'}")

    if "技術的" not in (root / "README.md").read_text(encoding="utf-8") if (root / "README.md").is_file() else False:
        warnings.append("README may not clearly separate instruction files from technical controls")

    return errors, warnings


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path)
    args = parser.parse_args()
    errors, warnings = validate(args.root)
    for warning in warnings:
        print(f"WARNING: {warning}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        print(f"VALIDATION_FAILED errors={len(errors)}", file=sys.stderr)
        return 1
    agent_count = len(list(args.root.rglob("AGENTS.md")))
    file_count = len([path for path in args.root.rglob("*") if path.is_file()])
    role_count = len(list(args.root.rglob("AI社員/役割定義.md")))
    print(f"検査合格 ファイル数={file_count} AGENTS.md数={agent_count} AI役割定義数={role_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
